### ISSUE TITLE
Encountered an error while running train.py

### ISSUE THREAD

**Issue by shuli1224** [LetterLiGo/SafeEar#6]
Hello，I'm currently trying to run the train.py code from the SafeEar project, and I encountered the following error:
`Traceback (most recent call last):
  File "/Project/SafeEar-main/train.py", line 123, in <module>
    train(cfg)
  File "/Project/SafeEar-main/train.py", line 96, in train
    to_save = system.audio_model.serialize()
  File "/anaconda3/envs/SafeEar1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'SafeEarTrainer' object has no attribute 'audio_model'`
Upon reviewing the code, I noticed that the SafeEarTrainer class does not seem to have an audio_model attribute defined.Could you please provide clarification on this issue? Is there a complete version of the code that includes the audio_model, or could you advise on how to resolve this?

**Comment by JusperLee** [comment]
Hello,

Thank you for reaching out. The error you encountered is due to the fact that the `SafeEarTrainer` class does not have an `audio_model` attribute. To resolve this, you can modify the line in `train.py` from:

```python
to_save = system.audio_model.serialize()
```

to:

```python
to_save = system.detect_model.serialize()
```

This change should help you proceed with running the code. If you have any further questions or issues, feel free to ask!

Best regards
